### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by youncyb** [CBHue/PyFuscation#2]
in 171 line:
new = "$" + ''.join([random.choice(string.ascii_letters + str(vNum)) for n in range(15)])
the str(vNum) will cause that the number in the first place, and a variable can't start with a number!

**Comment by CBHue** [comment]
Should be good to go now. Thanks!

new = "$" + ''.join([random.choice(string.ascii_letters) for n in range(8)])
VARs[i] = new + str(vNum)
